version: '3'
services:
  flask:
    build: .
    command: gunicorn -b 0.0.0.0:5005 run:app --reload
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=True
    ports:
      - "5005:5005"
    volumes:
      - ./:/root